export const FETCH_PRODUCT_REQUEST='FETCH_PRODUCT_REQUEST'
export const FETCH_PRODUCT_SUCCESS='FETCH_PRODUCT_SUCCESS'
export const FETCH_PRODUCT_FAILED='FETCH_PRODUCT_FAILED'

export const FETCH_PRODUCTBY_ID_REQUEST='FETCH_PRODUCTBY_ID_REQUEST'
export const FETCH_PRODUCTBY_ID_SUCCESS='FETCH_PRODUCTBY_ID_SUCCESS'
export const FETCH_PRODUCTBY_ID_FAILED='FETCH_PRODUCTBY_ID_FAILED'


export const SUBMIT_REVIEW='SUBMIT_REVIEW'

